apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: adjust
build:
  artifacts:
  - image: simple-app
    context: applications
    docker:
      dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
    - k8s_manifest/web
    - k8s_manifest/monitoring
